### ISSUE TITLE
Adding OnPlatform for Grid.RowDefinitions / Grid.ColumnDefinitions along side OnScreenSizeMarkup

### ISSUE THREAD

**Issue by JudicialCafe** [carolzbnbr/OnScreenSizeMarkup.Maui#6]
Hello, and thank you for the awesome package.

Currently for many controls I am able to use the OnPlatform feature to do my sizing without any issues. Such as.

 <Label.FontSize>

     <OnPlatform x:TypeArguments="x:Double">

         <On Platform="Android" Value="{markups:OnScreenSize Small='22', Medium='24', Large='30', ExtraLarge='35', Default='20'}"/>

         <On Platform="iOS" Value="{markups:OnScreenSize Small='23', Medium='25', Large='30', ExtraLarge='35', Default='20'}"/>

     </OnPlatform>

 </Label.FontSize>

This works great. But cant seem to implement the same features for Row / Column definitions in a grid

I have tried

<RowDefinition Height="{markups:OnScreenSize Small='22', Medium=**'{OnPlatform Android=100 iOS=200}',** Large='30', ExtraLarge='35', Default='20'}"

but this does not seem to work.

Thank you.

**Comment by carolzbnbr** [comment]
Hi,


Try this on your page.resources:

```xml
  <ResourceDictionary>
            <OnPlatform x:Key="SaveButtonRow" x:TypeArguments="GridLength">
                <OnPlatform.Platforms>
                    <On Platform="Android">
                        <markups:OnScreenSize FallbackType="{x:Type GridLength}"
                                              Default="*" 
                                              Medium="80"
                                              Large="80"/>
                    </On>
                    <On Platform="iOS">
                        <markups:OnScreenSize FallbackType="{x:Type GridLength}"
                                              Default="*" 
                                              Medium="60" />
                    </On>
                </OnPlatform.Platforms>
            </OnPlatform>

  </ResourceDictionary>

```

And then inside the page's content, declare your grid as is:

```xml
<Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="{StaticResource SaveButtonRow}"/>
            </Grid.RowDefinitions>

</Grid>
```

**Comment by JudicialCafe** [comment]
Thank you soo much.

**Comment by carolzbnbr** [comment]
Glad it worked.

Closing the issue since everything is working perfectly.
